package com.epac.cap.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DefaultStationId generated by hbm2java
 */
@Embeddable
public class DefaultStationId implements java.io.Serializable, Comparable<DefaultStationId> {
	/**
	 * 
	 */
	private static final long serialVersionUID = 970665110828219870L;
	private String categoryId;
	private String critiriaId;
	private String bindingTypeId;
	private String stationCategoryId;

	/**
	 * Default constructor
	 */
	public DefaultStationId() {
	}

	/**
	 * Constructor which sets all of the properties
	 */
	public DefaultStationId(String categoryId, String critiriaId, String bindingTypeId, String stationCategoryId) {
		this.categoryId = categoryId;
		this.critiriaId = critiriaId;
		this.bindingTypeId = bindingTypeId;
		this.stationCategoryId = stationCategoryId;
	}

	/**
	 * Accessor methods for categoryId
	 *
	 * @return categoryId  
	 */

	@Column(name = "Category_Id", nullable = false, length = 25)
	public String getCategoryId() {
		return this.categoryId;
	}

	/**
	 * @param categoryId the categoryId to set
	 */
	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * Accessor methods for critiriaId
	 *
	 * @return critiriaId  
	 */

	@Column(name = "Critiria_Id", nullable = false, length = 25)
	public String getCritiriaId() {
		return this.critiriaId;
	}

	/**
	 * @param critiriaId the critiriaId to set
	 */
	public void setCritiriaId(String critiriaId) {
		this.critiriaId = critiriaId;
	}

	/**
	 * @return the bindingTypeId
	 */
	@Column(name = "Binding_Type_Id", nullable = false, length = 25)
	public String getBindingTypeId() {
		return bindingTypeId;
	}

	/**
	 * @param bindingTypeId the bindingTypeId to set
	 */
	public void setBindingTypeId(String bindingTypeId) {
		this.bindingTypeId = bindingTypeId;
	}

	/**
	 * Accessor methods for stationCategoryId
	 *
	 * @return stationCategoryId  
	 */

	@Column(name = "Station_Category_Id", nullable = false, length = 25)
	public String getStationCategoryId() {
		return this.stationCategoryId;
	}

	/**
	 * @param stationCategoryId the stationCategoryId to set
	 */
	public void setStationCategoryId(String stationCategoryId) {
		this.stationCategoryId = stationCategoryId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DefaultStationId))
			return false;
		DefaultStationId castOther = (DefaultStationId) other;

		return ((this.getCategoryId() == castOther.getCategoryId()) || (this.getCategoryId() != null
				&& castOther.getCategoryId() != null && this.getCategoryId().equals(castOther.getCategoryId())))
				&& ((this.getCritiriaId() == castOther.getCritiriaId()) || (this.getCritiriaId() != null
						&& castOther.getCritiriaId() != null && this.getCritiriaId().equals(castOther.getCritiriaId())))
				&& ((this.getBindingTypeId() == castOther.getBindingTypeId()) || (this.getBindingTypeId() != null
						&& castOther.getBindingTypeId() != null && this.getBindingTypeId().equals(castOther.getBindingTypeId())))
				&& ((this.getStationCategoryId() == castOther.getStationCategoryId()) || (this.getStationCategoryId() != null
						&& castOther.getStationCategoryId() != null && this.getStationCategoryId().equals(castOther.getStationCategoryId())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCategoryId() == null ? 0 : this.getCategoryId().hashCode());
		result = 37 * result + (getCritiriaId() == null ? 0 : this.getCritiriaId().hashCode());
		result = 37 * result + (getBindingTypeId() == null ? 0 : this.getBindingTypeId().hashCode());
		result = 37 * result + (getStationCategoryId() == null ? 0 : this.getStationCategoryId().hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return categoryId + "_" + critiriaId + "_" + bindingTypeId + "_" + stationCategoryId ;
	}

	@Override
	public int compareTo(DefaultStationId o) {
		return new org.apache.commons.lang.builder.CompareToBuilder()
	    		.append(getCategoryId(), o.getCategoryId())
	    		.append(getCritiriaId(), o.getCritiriaId())
	    		.append(getBindingTypeId(), o.getBindingTypeId())
	    		.append(getStationCategoryId(), o.getStationCategoryId())
	    		.toComparison();
	}

}
