package com.epac.cap.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SubPartId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class SubPartId implements java.io.Serializable, Comparable<SubPartId> {
	private String topPartNum;
	private String subPartNum;

	/**
	 * Default constructor
	 */
	public SubPartId() {
	}

	/**
	 * Constructor which sets all of the properties
	 */
	public SubPartId(String topPartNum, String subPartNum) {
		this.topPartNum = topPartNum;
		this.subPartNum = subPartNum;
	}

	/**
	 * Accessor methods for topPartNum
	 *
	 * @return topPartNum  
	 */

	@Column(name = "Top_Part_Num", nullable = false, length = 25)
	public String getTopPartNum() {
		return this.topPartNum;
	}

	/**
	 * @param topPartNum the topPartNum to set
	 */
	public void setTopPartNum(String topPartNum) {
		this.topPartNum = topPartNum;
	}

	/**
	 * Accessor methods for subPartNum
	 *
	 * @return subPartNum  
	 */

	@Column(name = "Sub_Part_Num", nullable = false, length = 25)
	public String getSubPartNum() {
		return this.subPartNum;
	}

	/**
	 * @param subPartNum the subPartNum to set
	 */
	public void setSubPartNum(String subPartNum) {
		this.subPartNum = subPartNum;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubPartId))
			return false;
		SubPartId castOther = (SubPartId) other;

		return ((this.getTopPartNum() == castOther.getTopPartNum()) || (this.getTopPartNum() != null
				&& castOther.getTopPartNum() != null && this.getTopPartNum().equals(castOther.getTopPartNum())))
				&& ((this.getSubPartNum() == castOther.getSubPartNum())
						|| (this.getSubPartNum() != null && castOther.getSubPartNum() != null
								&& this.getSubPartNum().equals(castOther.getSubPartNum())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTopPartNum() == null ? 0 : this.getTopPartNum().hashCode());
		result = 37 * result + (getSubPartNum() == null ? 0 : this.getSubPartNum().hashCode());
		return result;
	}

	@Override
	public int compareTo(SubPartId o) {
		return new org.apache.commons.lang.builder.CompareToBuilder()
	    		.append(getTopPartNum(), o.getTopPartNum())
	    		.append(getSubPartNum(), o.getSubPartNum())
	    		.toComparison();
	}

}
